# Generated by Django 3.1.7 on 2021-04-07 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_phone', '0002_auto_20210405_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('hlr_status', models.IntegerField()),
                ('hlr_status_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('request_date', models.DateTimeField(default=datetime.datetime(2021, 4, 7, 22, 30, 52, 90591))),
            ],
        ),
    ]
