# Generated by Django 3.1.7 on 2021-04-07 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_phone', '0003_request_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_id',
            new_name='requests_id',
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 22, 41, 14, 114544)),
        ),
    ]
