# Generated by Django 3.1.7 on 2021-04-07 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_phone', '0004_auto_20210407_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='hlr_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='hlr_status_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 22, 56, 28, 996102)),
        ),
    ]
