# Generated by Django 3.1.7 on 2021-04-12 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_phone', '0005_auto_20210407_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.FloatField(default=80)),
            ],
        ),
        migrations.CreateModel(
            name='TempRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('price', models.FloatField()),
                ('phones', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 23, 41, 43, 775944)),
        ),
    ]
